apiVersion: apps/v1
kind: Deployment
metadata:
  name: ig
spec:
  template:
    spec:
      initContainers:
        # Copies certs from the ig-truststore-pem into the new-truststore volume
        - name: truststore-init
          image: ig
          imagePullPolicy: Always
          volumeMounts:
            - name: new-truststore
              mountPath: /truststore
            - name: ig-truststore-pem
              mountPath: /var/run/secrets/truststore
          command: [ "/home/forgerock/import-pem-certs.sh" ]
          env:
            # Path of the new truststore to create
            - name: TRUSTSTORE_PATH
              value: /truststore/igtruststore
            - name: TRUSTSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openig-secrets-env
                  key: IG_TRUSTSTORE_PASSWORD
            # Path to the pem file containing the certs to copy into the new truststore
            - name: IG_PEM_TRUSTSTORE
              value: "/var/run/secrets/truststore/ig-truststore.pem"

      containers:
      - name: core
        envFrom:
        - secretRef:
            name: openig-secrets-env
        - configMapRef:
            name: deployment-config
        imagePullPolicy: Always
        volumeMounts:
          - name: new-truststore
            mountPath: /var/ig/secrets/truststore
            readOnly: true
          - name: ig-ob-signing-key
            mountPath: /var/ig/secrets/open-banking
            readOnly: true
          - name: test-trusted-dir-keystore
            mountPath: /var/ig/secrets/test-trusted-directory
            readOnly: true
      volumes:
        # Empty volume where the igtruststore will be created by the initContainer, it can then be mounted into the ig container
        - name: new-truststore
          emptyDir: { }
        - name: ig-truststore-pem
          secret:
            secretName: ig-truststore-pem
            optional: false
        - name: ig-ob-signing-key
          secret:
            secretName: ig-ob-signing-key
            optional: false
        - name: test-trusted-dir-keystore
          secret:
            secretName: test-trusted-dir-keystore
            optional: false