namespace: dev
commonLabels:
  app.kubernetes.io/name: "forgerock"
resources:
- securebanking
- kustomizeConfig
- ingress.yaml

patchesStrategicMerge:
  - configmap.yaml
  - deployment.yaml
  - secret.yaml

images:
- name: ig
  newName: eu.gcr.io/sbat-gcr-develop/securebanking/gate/ig
  newTag: latest


