namespace: default
commonLabels:
  app.kubernetes.io/name: "forgerock"
resources:
# May need a nicer way of doing the release verison in future
- https://github.com/ForgeRock/forgeops/kustomize/base/ig?ref=release/7.2.0

secretGenerator:
- name: obri-ca
  files:
  - ca.crt
generatorOptions:
  disableNameSuffixHash: true
