apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
- name: ob-deployment-config
generatorOptions:
  disableNameSuffixHash: true
kind: Kustomization
images:
- name: europe-west4-docker.pkg.dev/sbat-gcr-develop/sapig-docker-artifact/securebanking/sapig-core
  newName: europe-west4-docker.pkg.dev/sbat-gcr-develop/sapig-docker-artifact/securebanking/ig
  newTag: latest-v4
patches:
  - path: configmap.yaml
  - path: secret.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: ig
    path: patch/deployment/ig-deployment-patch.yaml
  - target:
      version: v1
      kind: ConfigMap
      name: core-deployment-config
    path: patch/configmap/core-configmap-patch.yaml
  - patch: |-
      $patch: delete
      apiVersion: v1
      kind: Secret
      metadata:
        name: openig-secrets-env
resources:
  - https://github.com/SecureApiGateway/sapig-openbanking-uk-developer-envs/core/kustomize/overlay/defaults?ref=master
  - ingress.yaml
secretGenerator:
- name: ob-secrets
