apiVersion: v1
kind: ConfigMap
metadata:
  name: core-deployment-config
data:
  CLOUD_TYPE: "FIDC"
  BASE_FQDN: "dev-aic-ob.forgerock.financial"
  IG_FQDN: "sapig.dev-aic-ob.forgerock.financial"
  MTLS_FQDN: "mtls.sapig.dev-aic-ob.forgerock.financial"
  IDENTITY_PLATFORM_FQDN: "openam-sapig-nightly.forgeblocks.com"
  TRUSTEDDIR_FQDN: "test-trusted-directory.dev-aic-ob.forgerock.financial"
  USER_OBJECT: "alpha_user"
  IDENTITY_DEFAULT_USER_AUTHENTICATION_SERVICE: "PasswordGrant"
  IDENTITY_GOOGLE_SECRET_STORE_NAME: "ESV"
  IDENTITY_GOOGLE_SECRET_STORE_OAUTH2_CA_CERTS_SECRET_NAME: "esv-sapig-ob-am-oauth2-ca-certs"
